<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>ServerDoctor</RootNamespace>
    <AssemblyName>ServerDoctor</AssemblyName>
    <OutputType>Library</OutputType>
    <LangVersion>12.0</LangVersion>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ReferenceProtobufNet>true</ReferenceProtobufNet>
    <PackageFileName>$(AssemblyName).zip</PackageFileName>
    <CleanModOutputBeforeDeploy>true</CleanModOutputBeforeDeploy>
  </PropertyGroup>

  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
