<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin/$(Configuration)/</OutputPath>
    <AssemblyName>InterestingMeFixClient</AssemblyName>
    <RootNamespace>InterestingMeFixClient</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="interestingme">
      <HintPath>./lib/interestingme.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
