<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <SignAssembly>false</SignAssembly>
    <DelaySign>false</DelaySign>
    <AssemblyName>ClientFixes</AssemblyName>
    <RootNamespace>ClientFixes</RootNamespace>
    <PackageFileName>$(AssemblyName).zip</PackageFileName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
