<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin/$(Configuration)/</OutputPath>
    <AssemblyName>HerbariumBerryBushFix</AssemblyName>
    <RootNamespace>HerbariumBerryBushFix</RootNamespace>
    <Version>1.0.5</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <PackageFileName>$(AssemblyName)-v$(Version).zip</PackageFileName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
