<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <SignAssembly>false</SignAssembly>
    <DelaySign>false</DelaySign>
    <AssemblyName>BetterHandbook</AssemblyName>
    <RootNamespace>BetterHandbook</RootNamespace>
    <Version>1.0.9</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <PackageFileName>$(AssemblyName)-$(Version).zip</PackageFileName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="Always" />
    <None Include="assets/**/*" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
