<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin/$(Configuration)/</OutputPath>
    <AssemblyName>InterestingMeFix</AssemblyName>
    <RootNamespace>InterestingMeFix</RootNamespace>
    <Version>1.1.22</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <PackageFileName>$(AssemblyName)-v$(Version).zip</PackageFileName>
    <ReferenceVSEssentials>true</ReferenceVSEssentials>
    <ReferenceNewtonsoftJson>true</ReferenceNewtonsoftJson>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="interestingme">
      <HintPath>./lib/interestingme.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
