<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin/$(Configuration)/</OutputPath>
    <AssemblyName>StorageControllerClientFix</AssemblyName>
    <RootNamespace>StorageControllerClientFix</RootNamespace>
    <Version>1.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <PackageFileName>$(AssemblyName)-v$(Version).zip</PackageFileName>
    <ReferenceVSEssentials>true</ReferenceVSEssentials>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="storagecontroller">
      <HintPath>./lib/storagecontroller.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
