<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin/$(Configuration)/</OutputPath>
    <AssemblyName>FastCraftingGrid</AssemblyName>
    <RootNamespace>FastCraftingGrid</RootNamespace>
    <Version>1.0.4</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <PackageFileName>fastcraftinggrid-$(Version).zip</PackageFileName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="modinfo.json" CopyToOutputDirectory="Always" />
    <None Include="LICENSE" CopyToOutputDirectory="Always" Condition="Exists('LICENSE')" />
  </ItemGroup>
</Project>
