<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <SignAssembly>false</SignAssembly>
    <DelaySign>false</DelaySign>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>/home/garward/Games/Games/VintageStory/vintagestory/VintagestoryAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>/home/garward/Games/Games/VintageStory/vintagestory/VintagestoryLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>/home/garward/Games/Games/VintageStory/vintagestory/Lib/0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
