<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>./</OutputPath>
    <AssemblyName>InterestingMeFix</AssemblyName>
    <RootNamespace>InterestingMeFix</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <GameDirectory>/home/garward/Games/Games/VintageStory/vintagestory</GameDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(GameDirectory)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(GameDirectory)/VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(GameDirectory)/Mods/VSSurvivalMod.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(GameDirectory)/Mods/VSEssentials.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GameDirectory)/Lib/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameDirectory)/Lib/Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="interestingme">
      <HintPath>./lib/interestingme.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
